### ISSUE TITLE
Chocomilk GitHub action workflow not scheduled anymore

### ISSUE THREAD

**Issue by olifre** [open-circle-ltd/chocolatey.microsoft-office-deployment#35]
Dear @sbaerlocher ,

it seems the regular ChocoMilk GitHub action workflow is currently not triggered automatically anymore (last run 5 months ago, so no new version picked up since then and no package supporting Office 2024 LTSC pushed automatically). 
I guess GitHub just disabled the workflow once more after a short time of repo inactivity. 

To keep the workflow alive automatically, you may be interested in https://github.com/gautamkrishnar/keepalive-workflow (if you prefer, I can also prepare a PR adding that workflow here, just ping me :wink: ). 

Thanks a lot!

**Comment by FreeMinded** [comment]
@olifre thanks for pointing out the issue. I fixed and reactivated the the pipeline. The updated package is already available.
Would be very appreciated if you can prepare a PR for the keepalive. :pray:

**Comment by olifre** [comment]
Thanks @FreeMinded for merging the PR! 
I'll close this issue then as the schedule should be running again and stay running due to the keepalive workflow :+1: .
